id: IF7EE148D
ocr_import_info:
  timestamp: '2023-10-06T09:40:01.405771+00:00'
  batch_id: batch-1f06
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharmakyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-10-06 12:41:10.142122+00:00
last_modified: 2023-10-06 12:41:10.142130+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1219
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1219
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐུབ་པའི་དགོངས་པ་གསལ་བ།
  languages:
  - bo
  author: ས་སྐྱ་པཎྜི་ཏ་ཀུན་དགའ་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.883247428923279
  ocr_word_median_confidence_index: 0.94173855
bases:
  I1CZ1677:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1677
      total_pages: 376
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1677.txt
    statistics:
      ocr_word_median_confidence_index: 0.94173855
      ocr_word_mean_confidence_index: 0.883247428923279
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
